export const AUTH = {
  USER_DATA: 'USER_DATA',
  LOGGED_IN: 'LOGGED_IN',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  LOGIN_WITH_GOOGLE: 'LOGIN_WITH_GOOGLE',
  IMAGINARY_CLIENT: 'IMAGINARY_CLIENT',
  CURRENT_IMAGINARY_USER: 'CURRENT_IMAGINARY_USER',
}
