export const EXPENSES = {
  EXPENSES: 'EXPENSES',
  WEEKLY_EXPENSES: 'WEEKLY_EXPENSES',
  MONTHLY_EXPENSES: 'MONTHLY_EXPENSES',
  DATE_RANGE: 'DATE_RANGE',
  EXPENSES_SEARCH: 'EXPENSES_SEARCH',
} as const
