export const GOAL_QUERY_KEYS = {
  GOAL_KPI: 'GOAL_KPI',
  GOAL_SOURCE: 'GOAL_SOURCE',
  GOAL_PROPORTIONALITY: 'GOAL_PROPORTIONALITY',
  GOALS: 'GOALS',
  GOALS_PROGRESS: 'GOALS_PROGRESS',
  GOAL_DETAILS: 'GOAL_DETAILS',
  GOAL_TIMELINE: 'GOAL_TIMELINE',
}
