export const INCOME_STATEMENT_QUERY_KEYS = {
  INCOME_SOURCE: 'INCOME_SOURCE',
  INCOME_EXPENSE: 'INCOME_EXPENSE',
  INCOME_SOURCE_TYPES: 'INCOME_SOURCE_TYPES',
  INCOME_EXPENSE_TYPES: 'INCOME_EXPENSE_TYPES',
}
