export const LENDING = {
  TRANSACTIONS: 'LENDING_TRANSACTIONS',
  TRANSACTIONS_LIST: 'LENDING_TRANSACTIONS_LIST',
  ACCOUNTS: 'LENDING_ACCOUNTS',
  ACCOUNTS_DETAILS: 'LENDING_ACCOUNTS_DETAILS',
} as const
