export const storageKeys = {
  CURRENCY_PREFERENCE: 'CURRENCY_PREFERENCE',
  EXPENCES_NOTIFICATION_STATUS:'EXPENCES_NOTIFICATION_STATUS',
  NOTIFICATION_PERMISSION_RESPONSE:'NOTIFICATION_PERMISSION_RESPONSE'
}
