import { RFValue } from 'react-native-responsive-fontsize'

const DEFAULT_SCREEN_HEIGHT = 896

export const FontSizes = {
  size10: RFValue(10, DEFAULT_SCREEN_HEIGHT),
  size11: RFValue(11, DEFAULT_SCREEN_HEIGHT),
  size12: RFValue(12, DEFAULT_SCREEN_HEIGHT),
  size13: RFValue(13, DEFAULT_SCREEN_HEIGHT),
  size14: RFValue(14, DEFAULT_SCREEN_HEIGHT),
  size15: RFValue(15, DEFAULT_SCREEN_HEIGHT),
  size16: RFValue(16, DEFAULT_SCREEN_HEIGHT),
  size17: RFValue(17, DEFAULT_SCREEN_HEIGHT),
  size18: RFValue(18, DEFAULT_SCREEN_HEIGHT),
  size19: RFValue(19, DEFAULT_SCREEN_HEIGHT),
  size20: RFValue(20, DEFAULT_SCREEN_HEIGHT),
  size22: RFValue(22, DEFAULT_SCREEN_HEIGHT),
  size24: RFValue(24, DEFAULT_SCREEN_HEIGHT),
  size26: RFValue(26, DEFAULT_SCREEN_HEIGHT),
  size28: RFValue(28, DEFAULT_SCREEN_HEIGHT),
  size30: RFValue(30, DEFAULT_SCREEN_HEIGHT),
  size32: RFValue(32, DEFAULT_SCREEN_HEIGHT),
  size33: RFValue(33, DEFAULT_SCREEN_HEIGHT),
  size34: RFValue(34, DEFAULT_SCREEN_HEIGHT),
  size36: RFValue(36, DEFAULT_SCREEN_HEIGHT),
  size38: RFValue(38, DEFAULT_SCREEN_HEIGHT),
  size42: RFValue(42, DEFAULT_SCREEN_HEIGHT),
  size45: RFValue(45, DEFAULT_SCREEN_HEIGHT),
  size48: RFValue(48, DEFAULT_SCREEN_HEIGHT),
}
